[package]
name = "client2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-beta.3"
crossbeam-channel = "0.5.14"
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = [
    "serialize",
    "debug",
] }

[lib]
name = "client2"
path = "src/lib.rs"