[[drone]]
id = 1
connected_node_ids = [2, 3, 5, 6]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 7, 8, 9]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [1, 4, 7, 8, 9]
pdr = 0.14


[[drone]]
id = 4
connected_node_ids = [2, 3, 7, 8, 9]
pdr = 0.14



[[client]]
id = 5
connected_drone_ids = [1]

[[client]]
id = 6
connected_drone_ids = [1]



[[server]]
id = 7
connected_drone_ids = [4, 3, 2]

[[server]]
id = 8
connected_drone_ids = [4, 3, 2]

[[server]]
id = 9
connected_drone_ids = [4, 3, 2]



#-------------------------------------------
#[[drone]]
#id = 1
#connected_node_ids = [2, 3, 5,13,14]
#pdr = 0.05
#
#[[drone]]
#id = 2
#connected_node_ids = [1, 3, 4, 7,8,9,13,14]
#pdr = 0.03
#
#[[drone]]
#id = 3
#connected_node_ids = [1,2, 4, 7,8,9]
#pdr = 0.14
#
#
#[[drone]]
#id = 13
#connected_node_ids = [1,2, 7,8,9]
#pdr = 0.14
#
#[[drone]]
#id = 14
#connected_node_ids = [1,2, 7,8,9]
#pdr = 0.14
#
#
#
#[[client]]
#id = 4
#connected_drone_ids = [2,3]
#
#[[client]]
#id = 5
#connected_drone_ids = [1]
#
#
#
#[[server]]
#id = 7
#connected_drone_ids = [2, 3,13,14]
#
#[[server]]
#id = 8
#connected_drone_ids = [2, 3,13,14]
#
#[[server]]
#id = 9
#connected_drone_ids = [2, 3,13,14]